### ISSUE TITLE
Attempting to view certain branches in a ROOT TBrowser causes a crash of that TBrowser

### ISSUE THREAD

**Issue by jpasc27** [LDMXAnalysis/ldmx-sw#1262]
**Describe the bug**
Viewing my output root file in a TBrowser leads to a crash of the root browser, but only when certain branches (and their subsequent leaves) are selected. The specific branches for my file are listed in the **Additional context** and **Screenshots** sections, along with some warnings printed out to the terminal.

**To Reproduce**
1. Download these files: 
[ap_producer.txt](https://github.com/LDMX-Software/ldmx-sw/files/14043348/ap_producer.txt) - change extension to .py once downloaded
[mAp_050_uniform_23_brem.lhe.txt](https://github.com/LDMX-Software/ldmx-sw/files/14056241/mAp_050_uniform_23_brem.lhe.txt) - remove .txt extension once downloaded
[mAp_050_uniform_23_decay.lhe.txt](https://github.com/LDMX-Software/ldmx-sw/files/14056248/mAp_050_uniform_23_decay.lhe.txt) - remove .txt extension once downloaded

2. `ap_producer.py` is the config file. Since I am providing the dark brem and A' decay files, you can just set the run number to match the number on those file names, for clarity. The last value in the command below is the number of events - usually it is higher, but for these purposes a lower number will produce the same problem. Be sure you have sourced the ldmx-sw environment, then type:
`ldmx fire ap_producer.py 23 mAp_050_uniform_23_brem.lhe mAp_050_uniform_23_decay.lhe output.root 1500`

4. Open ROOT and attempt to view your `output.root` file in a TBrowser(). Click on different branches, and within each one, pick a leaf to try and get the respective histogram to show up.

**Desired behavior**
To be able to view every branch/leaf of every class in a ROOT TBrowser() without a crash.

**Screenshots**
The list of available branches in my `output.root` file
<img width="199" alt="Screenshot 2024-02-07 at 11 32 03 AM" src="https://github.com/LDMX-Software/ldmx-sw/assets/83837176/c5fd3073-ebfa-4f7a-a317-e0d93227e939">

**Environment:**
Output of `ldmx config`:

LDMX base directory: /sfs/qumulo/qhome/jlp4td/LDMX
uname: Linux udc-aw34-13c1 4.18.0-425.10.1.el8_7.x86_64 #1 SMP Thu Jan 12 16:32:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
OSTYPE: linux-gnu
Bash version: 4.4.20(1)-release
Display Port: 
Container Mounts: /sfs/qumulo/qhome/jlp4td/LDMX
Container Environments: 
Singularity Version: 1.2.2
Singularity File: /sfs/qumulo/qhome/jlp4td/LDMX/ldmx_dev_latest.sif

**Additional context**
When selecting the `output.root` file, these warnings appear in the terminal:
```
Warning in <TClass::Init>: no dictionary for class pair<int,ldmx::SimParticle> is available
Warning in <TClass::Init>: no dictionary for class ldmx::SimParticle is available
Warning in <TClass::Init>: no dictionary for class ldmx::SimTrackerHit is available
Warning in <TClass::Init>: no dictionary for class ldmx::SimCalorimeterHit is available
Warning in <TClass::Init>: no dictionary for class ldmx::HgcrocDigiCollection is available
Warning in <TClass::Init>: no dictionary for class ldmx::EcalHit is available
Warning in <TClass::Init>: no dictionary for class ldmx::CalorimeterHit is available
Warning in <TClass::Init>: no dictionary for class ldmx::HcalHit is available
Warning in <TClass::Init>: no dictionary for class ldmx::HcalVetoResult is available
Warning in <TClass::Init>: no dictionary for class ldmx::EventHeader is available
Warning in <TClass::Init>: no dictionary for class ldmx::RunHeader is available
```

**Attempting to view a histogram (leaf) in the SimParticles branch causes the TBrowser() to crash.** However, every other branch appears to be fine, at least for this one file I was looking at.

**Comment by tomeichlersmith** [comment]
I want to emphasize that this issue seems to be with _all_ event files output by ldmx-sw. I can observe a crash when trying to view the sim particles branches from a basic inclusive simualtion.
```
ldmx use pro v3.3.3
ldmx fire ${LDMX_BASE}/ldmx-sw/SimCore/test/basic.py
ldmx rootbrowse justSim_10_events.root
<crash>
```

I suspect this is a bug with ROOT 6.22/08 TTree::Draw since that is where the stack trace originates and alternative TBrowsers do not have this issue. e.g. JSROOT:

![image](https://github.com/LDMX-Software/ldmx-sw/assets/31970302/e27d0189-cca5-4863-9b7f-b3290bd404a6)

## TBrowser Alternatives
- [JSROOT](https://root.cern/js/) No installation necessary since its browser-based. Visit https://root.cern/js/latest/ and click on the the button with the three dots to "upload" a local file for inspection.
- [uproot-browser](https://github.com/scikit-hep/uproot-browser) Python based like uproot so install via pip. Not super well maintained, but you could also just use `uproot` directly.
- [ROOT::RBrowser](https://root.cern/doc/master/classROOT_1_1RBrowser.html) not in our version of ROOT in the container, but if you have access to a newer version of ROOT, might be worth trying out.

**Comment by tvami** [comment]
I think our approach to this is to have the ROOT update as discussed in https://github.com/LDMX-Software/docker/issues/102
After that's done, we should come back to this issue.

**Comment by tomeichlersmith** [comment]
Same issue with updated ROOT version.

The PyROOT doesn't even get around the printing a stacktrace for us 👍 
```
tom@zuko:~/code/ldmx/1262-obs-map$ denv config print 
denv_workspace="/home/tom/code/ldmx"
denv_name="ldmx"
denv_image="ldmx/dev:v5.0.0"
denv_mounts=""
denv_shell="/bin/bash -i"
denv_network="true"
podman version 3.4.4
LDMX_NUM_EVENTS=15
LDMX_RUN_NUMBER=7500
ASAN_OPTIONS=detect_leaks=0
XAUTHORITY=/home/tom/.Xauthority
DISPLAY=:0
DENV_NAME=ldmx
DENV_RUNNER=podman
DENV_IMAGE=ldmx/dev:v5.0.0
HOME=/home/tom/code/ldmx
tom@zuko:~/code/ldmx/1262-obs-map$ denv fire ../ldmx-sw/SimCore/test/basic.py 
... normal output
tom@zuko:~/code/ldmx/1262-obs-map$ denv rootbrowse justSim_10_events.root 
Press enter to exit. *** Break *** segmentation violation
Exception in thread Thread-1 (_process_root_events):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/ROOT/_application.py", line 95, in _process_root_events
    gSystem.ProcessEvents()
cppyy.ll.SegmentationViolation: bool TSystem::ProcessEvents() =>
    SegmentationViolation: segfault in C++; program state was reset
^CTraceback (most recent call last):
  File "/usr/local/bin/rootbrowse", line 55, in <module>
    sys.exit(execute())
             ^^^^^^^^^
  File "/usr/local/bin/rootbrowse", line 52, in execute
    return cmdLineUtils.rootBrowse(args.FILE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/cmdLineUtils.py", line 810, in rootBrowse
    _openBrowser(rootFile)
  File "/usr/local/lib/cmdLineUtils.py", line 802, in _openBrowser
    input("Press enter to exit.")
KeyboardInterrupt
 *** Break *** segmentation violation
 *** Break *** segmentation violation
Segmentation fault (core dumped)
```
