### ISSUE TITLE
Add validation installation to the just commands & rename the dir

### ISSUE THREAD

**Issue by tvami** [LDMXAnalysis/ldmx-sw#1439]
**Is your feature request related to a problem? Please describe.**

This describtion
https://github.com/LDMX-Software/ldmx-sw/tree/d7392d661674d7ca0f2b35ef4d4778899eec0d95/Validation#inside-ldmx
doesn't work anymore with `ldmx` being an alias for `just`

Also there is this text in the README
> This module cannot be run from ldmx-sw directory. import Validation prefers the local directory instead of the installed path so it tries to load from the ldmx-sw/Validation directory.
> We could fix this by renaming the package inside Validation or renaming the directory.

**Describe the solution you'd like**

- Add validation installation to the just commands.
- Rename the directory to Validate

**Comment by tvami** [comment]
I also run into this on UCSB POD
```
[vamitamas@pod-login1 src]$ denv  python3 -m Validation compareDir/  --systems ecal.shower_feats
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/vamitamas/iss1398-impr-ecal-dqm/ldmx-sw/Validation/src/Validation/__init__.py", line 4, in <module>
    from ._differ import Differ
  File "/home/vamitamas/iss1398-impr-ecal-dqm/ldmx-sw/Validation/src/Validation/_differ.py", line 8, in <module>
    import matplotlib.pyplot as plt
  File "/home/vamitamas/iss1398-impr-ecal-dqm/ldmx-sw/install/python/matplotlib/__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/home/vamitamas/iss1398-impr-ecal-dqm/ldmx-sw/install/python/matplotlib/cbook.py", line 32, in <module>
    from matplotlib import _api, _c_internal_utils
ImportError: cannot import name '_api' from partially initialized module 'matplotlib' (most likely due to a circular import) (/home/vamitamas/iss1398-impr-ecal-dqm/ldmx-sw/install/python/matplotlib/__init__.py)
```
so I'll fix that too
