### ISSUE TITLE
Enabling ECal veto causes crash in ldmx-app

### ISSUE THREAD

**Issue by JeremyMcCormick** [LDMXAnalysis/ldmx-sw#387]
```
#6  0x00007f23c705291d in PySys_GetObject (name=0x7f23c82f8d9a "modules") at Python/sysmodule.c:53
#7  0x00007f23c82e41ab in TPyClassGenerator::GetClass(char const*, bool, bool) () at /nfs/slac/g/ldmx/software/root/bindings/pyroot/src/TPyClassGenerator.cxx:42
#8  0x00007f23cb225566 in TClass::LoadClassCustom(char const*, bool) () at /nfs/slac/g/ldmx/software/root/core/meta/src/TClass.cxx:5429
#9  0x00007f23cb22d2cb in TClass::GetClass(char const*, bool, bool) () at /nfs/slac/g/ldmx/software/root/core/meta/src/TClass.cxx:3003
#10 0x00007f23cb23239c in TBuildRealData::Inspect(TClass*, char const*, char const*, void const*, bool) () at /nfs/slac/g/ldmx/software/root/core/meta/src/TClass.cxx:808
#11 0x00007f23bbbb662c in TCling::InspectMembers(TMemberInspector&, void const*, TClass const*, bool) () at /nfs/slac/g/ldmx/software/root/core/meta/src/TCling.cxx:2300
#12 0x00007f23cb226380 in TClass::CallShowMembers(void const*, TMemberInspector&, bool) const () at /nfs/slac/g/ldmx/software/root/core/meta/src/TClass.cxx:2131
#13 0x00007f23cb19ff75 in TMemberInspector::InspectMember(char const*, void const*, char const*, bool) () at /nfs/slac/g/ldmx/software/root/core/base/src/TMemberInspector.cxx:145
#14 0x00007f23bbbb6748 in TCling::InspectMembers(TMemberInspector&, void const*, TClass const*, bool) () at /nfs/slac/g/ldmx/software/root/core/meta/src/TCling.cxx:2321
#15 0x00007f23bbbb6a10 in TCling::InspectMembers(TMemberInspector&, void const*, TClass const*, bool) () at /nfs/slac/g/ldmx/software/root/core/meta/src/TCling.cxx:2410
#16 0x00007f23cb226380 in TClass::CallShowMembers(void const*, TMemberInspector&, bool) const () at /nfs/slac/g/ldmx/software/root/core/meta/src/TClass.cxx:2131
#17 0x00007f23cb230adf in TClass::BuildRealData(void*, bool) () at /nfs/slac/g/ldmx/software/root/core/meta/src/TClass.cxx:1986
#18 0x00007f23cabcf0fb in TBufferFile::ReadClassBuffer(TClass const*, void*, int, unsigned int, unsigned int, TClass const*) () at /nfs/slac/g/ldmx/software/root/io/io/src/TBufferFile.cxx:3718
#19 0x00007f23cb25bcc2 in TStreamerString::Streamer(TBuffer&) () at /nfs/slac/g/ldmx/software/root/core/meta/src/TStreamerElement.cxx:1642
#20 0x00007f23cabd317c in TBufferFile::ReadObjectAny(TClass const*) () at /nfs/slac/g/ldmx/software/root/rbuild/include/TClass.h:547
#21 0x00007f23cb2030a0 in TObjArray::Streamer(TBuffer&) () at /nfs/slac/g/ldmx/software/root/core/cont/src/TObjArray.cxx:444
#22 0x00007f23cabd317c in TBufferFile::ReadObjectAny(TClass const*) () at /nfs/slac/g/ldmx/software/root/rbuild/include/TClass.h:547
#23 0x00007f23cac2ba07 in TBuffer& operator>><TObjArray>(TBuffer&, TObjArray*&) () at /nfs/slac/g/ldmx/software/root/rbuild/include/TBuffer.h:380
#24 0x00007f23cac2afa3 in TStreamerInfo::Streamer(TBuffer&) () at /nfs/slac/g/ldmx/software/root/io/io/src/TStreamerInfo.cxx:4994
#25 0x00007f23cabd317c in TBufferFile::ReadObjectAny(TClass const*) () at /nfs/slac/g/ldmx/software/root/rbuild/include/TClass.h:547
#26 0x00007f23cb200397 in TBuffer& operator>><TObject>(TBuffer&, TObject*&) () at /nfs/slac/g/ldmx/software/root/rbuild/include/TBuffer.h:380
#27 0x00007f23cb2000c8 in TList::Streamer(TBuffer&) () at /nfs/slac/g/ldmx/software/root/core/cont/src/TList.cxx:1024
#28 0x00007f23cac0ded5 in TKey::ReadObjWithBuffer(char*) () at /nfs/slac/g/ldmx/software/root/io/io/src/TKey.cxx:951
#29 0x00007f23cabe295b in TFile::GetStreamerInfoList() () at /nfs/slac/g/ldmx/software/root/io/io/src/TFile.cxx:1336
#30 0x00007f23cabe0a9a in TFile::ReadStreamerInfo() () at /nfs/slac/g/ldmx/software/root/io/io/src/TFile.cxx:3385
#31 0x00007f23cabeb3ae in TFile::Init(bool) () at /nfs/slac/g/ldmx/software/root/io/io/src/TFile.cxx:851
#32 0x00007f23cabec756 in TFile::TFile(char const*, char const*, char const*, int) () at /nfs/slac/g/ldmx/software/root/io/io/src/TFile.cxx:516
#33 0x00007f23c6cf52ec in ldmx::EventFile::EventFile(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, int) () from /u/ey/jeremym/ldmx-dev/ldmx-sw/install/lib/libFramework.so
#34 0x00007f23c6cf572f in ldmx::EventFile::EventFile(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, int) () from /u/ey/jeremym/ldmx-dev/ldmx-sw/install/lib/libFramework.so
#35 0x00007f23c6d0ba78 in ldmx::Process::run() () from /u/ey/jeremym/ldmx-dev/ldmx-sw/install/lib/libFramework.so
#36 0x00000000004019ac in main ()
```

**Comment by omar-moreno** [comment]
This was resolved with the latest BDT updates.
